[flake8]
extend-ignore = A003, Q000, VNE003, CCE001, CCR001, B008, I001, B001, E722, CFQ004, CFQ002, F821, I003
exclude =
    .git,
    __pycache__,
    venv,
    ./auth_service/src/alembic/versions/,
