"""Update user, add refresh_tokens, add login_history

Revision ID: 86ca8b001684
Revises: e36203d30cf7
Create Date: 2025-03-04 16:28:38.691476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86ca8b001684'
down_revision: Union[str, None] = 'e36203d30cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE login_history (
            entry_id SERIAL,
            user_id INTEGER NOT NULL REFERENCES users(id),
            login_time TIMESTAMP NOT NULL DEFAULT NOW(),
            ip_address VARCHAR(45),
            user_agent TEXT,
            action VARCHAR(50) NOT NULL,
            PRIMARY KEY (entry_id, login_time)
        ) PARTITION BY RANGE (login_time);
    """)
    op.create_table('refresh_tokens',
        sa.Column('token_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('refresh_token', sa.String(length=255), nullable=False),
        sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('revoked', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_id'), 'refresh_tokens', ['token_id'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'updated_at')
    op.drop_index(op.f('ix_refresh_tokens_token_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.execute("DROP TABLE IF EXISTS login_history CASCADE;")
    # ### end Alembic commands ###
