input {
  gelf {
    type => "docker"
    port => "5044"
  }
  udp {
    codec => "json"
    port => "5045"
  }
}
filter {

}
output {
  stdout {
  }
  if "nginx" in [tag] or "nginx" in [tags] {
      elasticsearch {
        hosts => [ "${ES_HOST}" ]
        index => "nginx-%{+YYYY.MM.dd}"
      }
  } else if "mongo_user_api" in [tag] or "mongo_user_api" in [tags] {
      elasticsearch {
          hosts => [ "${ES_HOST}" ]
          index => "mongo_user_api-%{+YYYY.MM}"
       }
   } else if "content_service" in [tag] or "content_service" in [tags] {
       elasticsearch {
           hosts => [ "${ES_HOST}" ]
           index => "content_service-%{+YYYY.MM}"
       }
   } else if "auth_service" in [tag] or "auth_service" in [tags] {
       elasticsearch {
           hosts => [ "${ES_HOST}" ]
           index => "auth_service-%{+YYYY.MM}"
      }
  }
}