worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;

    sendfile        on;
    tcp_nodelay     on;
    tcp_nopush      on;

    client_max_body_size 8m;

    gzip on;
    gzip_min_length 1000;
    gzip_types
        text/plain
        text/css
        application/json
        application/x-javascript
        text/xml
        text/javascript;

    proxy_http_version 1.1;
    proxy_redirect     off;
    proxy_set_header   Host              $host;
    proxy_set_header   X-Request-ID      $request_id;
    proxy_set_header   X-Real-IP         $remote_addr;
    proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header   X-Forwarded-Proto $scheme;
    proxy_set_header   Connection        "keep-alive";
    proxy_set_header   Upgrade           $http_upgrade;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    'request_id=$request_id';
    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log warn;

    set_real_ip_from  172.28.0.0/16;
    real_ip_header    X-Forwarded-For;

    server_tokens   off;

    server {
        listen 80;

        location /assets/ {
            alias /app/frontend_service/frontend/assets/;
        }

        location /js/ {
            alias /app/frontend_service/frontend/js/;
        }

        location / {
            root /app/frontend_service/frontend;
            try_files $uri /index.html;
        }

        location /api/v1/auth/ {
            proxy_pass http://auth-service:8000/api/v1/auth/;
        }

        location /api/v1/mongo/ {
            proxy_pass http://mongo_user_api:8000/api/v1/auth/;
        }

        location /admin/ {
            proxy_pass http://admin-service:8000/admin/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/v1/ {
            proxy_pass http://content-service:8000/api/v1/;
        }

        location /docs {
            proxy_pass http://swagger-service:8000/docs;
        }

        location /openapi.json {
            proxy_pass http://swagger-service:8000/openapi.json;
        }

        location /api/v1/ugc/docs {
            proxy_pass http://ugc:8000/api/v1/ugc/docs;
        }

        location /api/v1/ugc/openapi.json {
            proxy_pass http://ugc:8000/api/v1/ugc/openapi.json;
        }

        location /api/v1/ugc/ {
            proxy_pass http://ugc:8000/api/v1/ugc/;
        }

        location /static/ {
            alias /opt/staticfiles/;
            access_log off;
            expires 30d;
        }
    }
}