# flake8: noqa
# Generated by Django 4.2.11 on 2025-09-09 16:31

from __future__ import annotations

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Тема"
                    ),
                ),
                ("body", models.TextField(verbose_name="Текст")),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("websocket", "WebSocket"),
                        ],
                        default="email",
                        max_length=16,
                        verbose_name="Канал доставки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
            ],
            options={
                "verbose_name": "Шаблон",
                "verbose_name_plural": "Шаблоны",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push"),
                            ("websocket", "WebSocket"),
                        ],
                        help_text="На этапе админки просто прокидываем канал; персонализация на стороне воркера.",
                        max_length=16,
                        verbose_name="Канал доставки",
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        default="all",
                        help_text="Напр.: 'all', 'segment:premium', 'user_ids:1,2,3'",
                        max_length=255,
                        verbose_name="Аудитория",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("immediate", "Сразу"),
                            ("delayed", "Отложенная"),
                            ("cron", "Повторяющаяся (cron)"),
                        ],
                        default="immediate",
                        max_length=16,
                        verbose_name="Тип расписания",
                    ),
                ),
                (
                    "delay_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Только для отложенных задач.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Задержка, сек.",
                    ),
                ),
                (
                    "cron",
                    models.CharField(
                        blank=True,
                        help_text="Только для повторяющихся задач. Пример: '0 12 * * FRI'",
                        max_length=128,
                        null=True,
                        verbose_name="Cron-выражение",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("scheduled", "Запланирована"),
                            ("running", "Выполняется"),
                            ("finished", "Завершена"),
                            ("canceled", "Отменена"),
                            ("failed", "Ошибка"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Создано"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Обновлено"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="broadcasts.template",
                        verbose_name="Шаблон",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кампания",
                "verbose_name_plural": "Кампании",
                "ordering": ("-updated_at",),
            },
        ),
    ]
